name: Build and test workflow
on:
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.2
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.2
        with: 
          java-version: 1.8
      - name: Grant permission for gradlew
        run: chmod +x gradlew
      - name: Clean project
        run: ./gradlew clean
      - name: Build debug
        run: /.gradlew assembleDebug
      - name: Build release
        run: ./gradlew assembleRelease
      - name: Run Lint check
        run: ./gradlew lintDebug
